categories: categories
search: search
tags: tags
tagcloud: tag cloud
tweets: tweets
prev: previous
next: next
comment: comments
archive_a: archives
archive_b: "Archives: %s"
page: page %d
recent_posts: recent posts
article: article
