categories: categories
search: search
tags: tags
tagcloud: tag cloud
tweets: tweets
prev: previous
next: next
comment: comments
archive_a: archives
archive_b: "Archives: %s"
page: page %d
recent_posts: recent posts
article: article
prev_article: previous article
next_article: next article
old_article_disclaimer_header: This article quite old.
old_article_disclaimer: Content may be outdated and/or links may be broken.
